<?php

/**
 * @file
 * Contains eventcreator.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eventcreator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eventcreator module.
    case 'help.page.eventcreator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Event Management Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function eventcreator_theme() {
  $theme = [];
  $theme['anonyreg'] = [
    'render element' => 'elements',
    'file' => 'anonyreg.page.inc',
    'template' => 'anonyreg',
  ];
  $theme['anonyreg_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'anonyreg.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function eventcreator_theme_suggestions_anonyreg(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#anonyreg'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'anonyreg__' . $sanitized_view_mode;
  $suggestions[] = 'anonyreg__' . $entity->bundle();
  $suggestions[] = 'anonyreg__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'anonyreg__' . $entity->id();
  $suggestions[] = 'anonyreg__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
